apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-pvc
  namespace: bitwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
